### ISSUE TITLE
Data not downloadable

### ISSUE THREAD

**Issue by vincentheddesheimer** [emanlapponi/talk-of-norway#7]
Hi all,

I would love to work with your corpus.
However when trying to download the data (both by clicking on link or through the terminal) I get an error message and it does not work. In particular I get the response "403 Forbidden: You don't have permission to access this resource." 

Thankful for any help!

**Comment by fatimaaaaaaa** [comment]
Also having this issue! I'll try reaching out to the authors via mail

**Comment by martigso** [comment]
Thanks for letting us know! We have done some investigating, and will probably have to find a new solution for hosting the data. I'll let you know when we have landed that.

**Comment by erikve** [comment]
Thanks for the heads-up @vincentheddesheimer and @fatimaaaaaaa, the download link has been updated now.
